### ISSUE TITLE
핸드폰이 90도 이상 기운 상태로 스위치를 누르면 안내사항 없이 바로 스위치 꺼짐

### ISSUE THREAD

**Issue by dntjr8096** [Nexters/zaza-android#44]
핸드폰이 90도 이상 기운 상태로 스위치를 누르면 안내사항 없이 바로 스위치 꺼짐

**Comment by conquerex** [comment]
[리팩] 휴대폰 가로 모드 상태에서 다시 화면을 위로 올라간 상태로 했을 때의 경우를 얘기하는 것
제가 작업합니다.

**Comment by conquerex** [comment]
@QURIAN 
개발 완료. 확인해주세요.
