### ISSUE TITLE
알람 설정 시 x버튼, 뒤로가기 버튼 동작이 다름

### ISSUE THREAD

**Issue by dntjr8096** [Nexters/zaza-android#46]
1. 알람 설정 시 x버튼을 눌렀다 들어오면 시간이 +6 -> +30 되는 이상한 현상이 발생함
(저장 x)
2. 알람 설정 시 뒤로가기 버튼을 누르면 저장은 똑같이 안되지만 동작이 다른 듯 함

**Comment by conquerex** [comment]
x버튼을 "저장"글자로

**Comment by conquerex** [comment]
9월 15일까지

**Comment by QURIAN** [comment]
1. 우하단 **뒤로가기**(안드로이드 기본 버튼) 선택시
> 저장하고, 이전페이지(메인)으로 이동 
Best : 하단에 한줄로 _**'저장되었습니다.'**_ 텍스트가 뜸 << 토스트 메시지

2. 우상단 **닫기버튼** 선택시
> 저장하지 않고, 이전페이지(메인)으로 이동
Best : 팝업으로 _**'저장하지 않고 나가시겠습니까?.'**_ , 예, 아니오 << 팝업창 커스텀은 해야 함  

*** 하단에 취소 저장이 없는 컨셉으로 가는 것도 나쁘지 않은 것 같아서 버튼 추가내용은 없답니다.**
