### ISSUE TITLE
알람설정 화면에서 요일 설정 버튼이 텍스트와 일치하지 않음

### ISSUE THREAD

**Issue by QURIAN** [Nexters/zaza-android#53]
그리고 잘 안눌림 ㅇㅅㅠ

**Comment by conquerex** [comment]
제가 진행할게요. [리팩]

**Comment by conquerex** [comment]
개발 완료. 
터치 이펙트는 제거해서 터치감에 이질감이 없도록 하였음.
터치존을 더 넓게함

**Comment by conquerex** [comment]
@QURIAN 확인해주세요

**Comment by conquerex** [comment]
개발 완료.
터치 이펙트는 제거해서 터치감에 이질감이 없도록 하였음.
터치존을 더 넓게함

@QURIAN 확인해주세요

**Comment by QURIAN** [comment]
잘됩니다!
