### ISSUE TITLE
모이는 꿈(그라데이션)이 중복으로 표기 되는 경우

### ISSUE THREAD

**Issue by QURIAN** [Nexters/zaza-android#55]
불러오는 꿈이 중복되는 경우가 있는데, 확인이 필요합니다.
그라데이션에서 랜덤으로 자르는 걸로 알아서 같은 그라데이션이라도 자르는 부분이 달라서 중복이 안되야 하는데, 중복이 됩니다.(제 기준으로는 꽤 있음)

로컬에 저장하는 이슈나, 자르는 부분이 중복일 수 밖에 없는 이슈가 있다면
3 colunm 으로 그라데이션을 불러오니 12개 기준으로 같은 꿈을 불러 오지 않는 조건을 설정하면 중복이 안될 것 같아요

**Comment by wow5468** [comment]
중복이 발생할 수 밖에 없습니다. 현재 기기에서 받은 그레디언트 목록을 클라이언트에서 받지 않습니다. 최대한 할 수 있는 방법은 180도 회전시키는 방법입니다. 좀 더 많은 그라디언트 샘플을 보내 주신다면 더 좋을 거 같습니다. (물론 가장 좋은 방법은 그라디언트를 randomly 생성하게 하는 방법입니다.) @QURIAN

**Comment by QURIAN** [comment]
음 그럼 같은 이미지더라도 캡쳐되는 범위가 다르면(randomly) 좋을 것 같은데 고민해주세여! @wow5468

**Comment by wow5468** [comment]
5220개 이미지 만들어서 업로드함.
