### ISSUE TITLE
알람시간 선택시 확인, 취소버튼이 너무 간격이 멀어요

### ISSUE THREAD

**Issue by QURIAN** [Nexters/zaza-android#56]
제플린 방금 확인했는데, 디자인이 머네요 허헣
아이폰유저라 안드로이드 표현이 생소할 수도 있을 것 같네요.. 

구글이나 삼성처럼 1/2 버튼에 중앙정렬하면 좋을 것 같은데
이건 연진님하고 이야기해볼게여

**Comment by conquerex** [comment]
[리팩] 제가 합니다.

**Comment by conquerex** [comment]
개발 완료.
터치 영역이 절반이 되도록 하였음

@QURIAN 확인해주세요

**Comment by QURIAN** [comment]
해결 완료!
