### ISSUE TITLE
꿈모으기 화면과 상세보기 화면의 이미지 매칭

### ISSUE THREAD

**Issue by QURIAN** [Nexters/zaza-android#58]
꿈모으기 화면에서 보이는 이미지(간단한 원형 그라데이션), 
상세화면을 눌렀을때 보이는 이미지(전체화면 그라데이션)
이 2개 이미지가 너무 상이합니다. 

비슷한 느낌이 나도록 하면 좋을 것 같습니다.
이미지가 다르게 잘리는 이유를 같이 파악하고, 이미지가 시작되는 부분을 정의하면 좋을 것 같아요!

**Comment by dntjr8096** [comment]
이 부분은 저장을 하는 부분에서 결정되는 거라 그 부분을 상의해봐야 할 것 같습니다!

**Comment by wow5468** [comment]
https://us-central1-zaza-249404.cloudfunctions.net/getImage 에서 보시면 배경이미지와 버튼이미지가 있습니다. 배경이미지를 갖고 버튼 이미지를 만들었으며.. 상이하다면.. 어떻게 해결해야할지..
